name: Check Git and Azure CLI Installation

on:
  workflow_dispatch:
    inputs:
      azure-client-id:
        description: "Azure Client ID"
        required: true
      azure-tenant-id:
        description: "Azure Tenant ID"
        required: true
      azure-subscription-id:
        description: "Azure Subscription ID"
        required: true

jobs:
  check-git-and-azure-cli:
    runs-on: self-hosted # Or change to `ubuntu-latest` for GitHub-hosted runners
    steps:
      # Step 1: Check if Git is installed
      - name: Check if Git is installed
        run: |
          if command -v git &> /dev/null; then
            echo "Git is installed."
            git --version
          else
            echo "Git is not installed."
            exit 1
          fi
        shell: bash
      
      # Step 2: Test MSI Endpoint
      - name: Test MSI Endpoint
        run: |
          curl -v http://169.254.169.254/metadata/identity/oauth2/token?api-version=2019-08-01&resource=https://management.azure.com -H Metadata:true
      
      # Step 3: Authenticate with Azure using Managed Identity
      - name: Authenticate with Azure using Managed Identity
        run: |
          az login --identity --username ${{ github.event.inputs.azure-client-id }}
          az account set --subscription ${{ github.event.inputs.azure-subscription-id }}
        shell: bash