name: Test Changed Folders

on:
  pull_request:
    branches:
      - main
  workflow_dispatch: # For manual testing

jobs:
  test-changed-folders:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Identify changed files and deduce folders
      - name: Identify changed folders
        id: changed_folders
        run: |
            if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "Running in a pull request context..."
            CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD)
            else
            echo "Not a pull request. Assuming manual run or push event..."
            if git rev-parse HEAD^ &> /dev/null; then
                CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
            else
                CHANGED_FILES=$(git ls-tree --name-only -r HEAD)
            fi
            fi
        
            echo "Changed files detected:"
            echo "$CHANGED_FILES"
        
            # Extract folders from file paths
            CHANGED_FOLDERS=$(echo "$CHANGED_FILES" | grep -E '\.(py|platform|ipynb|json)$' | cut -d'/' -f1 | sort | uniq)
            echo "Changed folders detected:"
            echo "$CHANGED_FOLDERS"
        
            echo "folders=$CHANGED_FOLDERS" >> $GITHUB_ENV
        shell: bash

      # Step 3: Log the results
      - name: Log detected folders
        run: |
          echo "Detected changed folders:"
          echo "$folders"
        shell: bash