name: Check Git Installation

on:
    workflow_dispatch: # Trigger manually
        inputs:
            azure-client-id:
                description: "Azure Client ID"
                required: true
            azure-tenant-id:
                description: "Azure Tenant ID"
                required: true
            azure-subscription-id:
                description: "Azure Subscription ID"
                required: true

jobs:
  check-git:
    runs-on: self-hosted # Or change to `ubuntu-latest` for GitHub-hosted runners
    steps:
      - name: Check if Git is installed
        run: |
          if command -v git &> /dev/null; then
            echo "Git is installed."
            git --version
          else
            echo "Git is not installed."
            exit 1
          fi
        shell: bash

      # Check Azure CLI installation
      - name: Authenticate with Azure using Managed Identity
        run: |
          az login --identity --username ${{ github.event.inputs.azure-client-id }}
          az account set --subscription ${{ github.event.inputs.azure-subscription-id }}
        shell: bash    