name: Identify Changed Files and Folders

on:
  workflow_dispatch: # Manually triggered for testing

jobs:
  identify-changes:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Identify changed files
      - name: Get changed files
        id: changed_files
        run: |
          if git rev-parse HEAD^ &> /dev/null; then
            echo "Fetching changed files between HEAD and HEAD^..."
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            echo "No previous commit found. Fetching all files in HEAD..."
            CHANGED_FILES=$(git ls-tree --name-only -r HEAD)
          fi

          echo "Changed files detected:"
          echo "$CHANGED_FILES"
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_ENV

      # Step 3: Deduce folders from the changed files
      - name: Extract unique folders
        id: unique_folders
        run: |
          FOLDERS=$(echo "$CHANGED_FILES" | grep -E '\.(py|platform|ipynb|json)$' | cut -d'/' -f1 | sort | uniq)
          echo "Unique folders detected:"
          echo "$FOLDERS"
          echo "folders=$FOLDERS" >> $GITHUB_ENV

      # Step 4: Output results
      - name: Display results
        run: |
          echo "Changed files:"
          echo "$CHANGED_FILES"
          echo "Folders:"
          echo "$FOLDERS"