name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  STORAGE_ACCOUNT: ${{ vars.CODE_STORAGE_ACCOUNT }}
  FABRIC_DEPLOYMENT_HUB_URL: ${{ vars.FABRIC_DEPLOYMENT_HUB_URL }}
  WORKSPACE_IDS: ${{ vars.WORKSPACE_IDS }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Obtain the modified folders list using GitHub's API
      - name: Get modified folders from GitHub API
        id: modified_folders
        run: |
          MODIFIED_FOLDERS=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files | \
            jq -r '.[].filename | split("/")[0]' | sort | uniq)
          echo "Modified folders detected:"
          echo "$MODIFIED_FOLDERS"
          echo "folders=$MODIFIED_FOLDERS" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash

      # Step 3: Authenticate with Azure using Managed Identity
      - name: Authenticate with Azure
        run: |
          az login --identity

      # Step 4: Upload repository to shared storage
      - name: Upload repository to shared storage
        run: |
          azcopy copy "$GITHUB_WORKSPACE" "https://${{ env.STORAGE_ACCOUNT }}.blob.core.windows.net/$(uuidgen)" --recursive

      # Step 5: Call the deployment API
      - name: Call Deployment API
        run: |
          curl -X POST "$FABRIC_DEPLOYMENT_HUB_URL/api/Deployments" \
            -H "Content-Type: application/json" \
            -d '{
              "workspaceIds": [${{ env.WORKSPACE_IDS }}],
              "repoContainer": "<container_name>",
              "modifiedFolders": ["'$MODIFIED_FOLDERS'"]
            }'