name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  STORAGE_ACCOUNT: ${{ vars.CODE_STORAGE_ACCOUNT }}
  FABRIC_DEPLOYMENT_HUB_URL: ${{ vars.FABRIC_DEPLOYMENT_HUB_URL }}
  WORKSPACE_IDS: ${{ vars.WORKSPACE_IDS }}

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Step 1: Ensure the ACA environment has Git installed
      - name: Install Git (if necessary)
        run: |
          if ! command -v git &> /dev/null; then
            echo "Git not found. Installing..."
            apt-get update && apt-get install -y git
          fi
          git --version

      # Step 2: Check out the repository
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 3: Identify modified folders
      - name: Get modified folders
        id: modified_folders
        run: |
          MODIFIED_FOLDERS=$(git diff --name-only origin/main...HEAD | cut -d'/' -f1 | sort | uniq)
          echo "Modified folders detected:"
          echo "$MODIFIED_FOLDERS"
          echo "folders=$MODIFIED_FOLDERS" >> $GITHUB_ENV
        shell: bash

      # Step 4: Authenticate with Azure using Managed Identity
      - name: Authenticate with Azure
        run: |
          az login --identity

      # Step 5: Upload repository to shared storage
      - name: Upload repository to shared storage
        run: |
          azcopy copy "$GITHUB_WORKSPACE" "https://${{ env.STORAGE_ACCOUNT }}.blob.core.windows.net/$(uuidgen)" --recursive

      # Step 6: Call the deployment API
      - name: Call Deployment API
        run: |
          curl -X POST "$FABRIC_DEPLOYMENT_HUB_URL/api/Deployments" \
            -H "Content-Type: application/json" \
            -d '{
              "workspaceIds": [${{ env.WORKSPACE_IDS }}],
              "repoContainer": "<container_name>",
              "modifiedFolders": ["'$MODIFIED_FOLDERS'"]
            }'
